config/routes.rb
Crm::Application.routes.draw do
  devise_for :users

  resources :customers
  resources :notes

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	belongs_to :user
  attr_accessible :address_city, :address_state, :address_state, :address_street, :email, :id, :name_company, :name_first, :name_last, :phone, :postal_code, :image
  mount_uploader :image, ImageUploader
  attr_accessible :image

end

app/models/notes.rb
class Notes < ActiveRecord::Base
	belongs_to :customer

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :customers
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :id
  # attr_accessible :title, :body

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_filter :authenticate_user!
  # GET /customers
  # GET /customers.json

  def create  
    @customer = Customer.new(params[:customer])
    @customer.user_id = current_user.id

    if @customer.save
      flash[:notice] = "Successfully created customer."
        redirect_to(:action => 'index')
    else
      render('new')
    end
  end
  

  def index
    #instead of returning all customers we can filter by only showing 
    #customers belonging to the current_user
    @customers = current_user.customers
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer, :html => {:multipart => true} do |f| %>
  
  <%= f.hidden_field :id %>
  
  <p>
    <%= f.file_field :image %>
  </p>
  
  <div class="control-group">
    <%= f.label :name_first, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name_first, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name_last, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name_last, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name_company, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name_company, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address_street, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address_street, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address_city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address_city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address_state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address_state, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :postal_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :postal_code, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customers_path, :class => 'btn' %>

  </div>

<% end %>

app/views/customers/edit.html.erb
<%- model_class = Customer -%>
 
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/index.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name_first) %></th>
      <th><%= model_class.human_attribute_name(:name_last) %></th>
      <th><%= model_class.human_attribute_name(:name_company) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:address_street) %></th>
      <th><%= model_class.human_attribute_name(:address_city) %></th>
      <th><%= model_class.human_attribute_name(:address_state) %></th>
      <th><%= model_class.human_attribute_name(:postal_code) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.id, customer_path(customer) %></td>
        <td><%= customer.name_first %></td>
        <td><%= customer.name_last %></td>
        <td><%= customer.name_company %></td>
        <td><%= customer.email %></td>
        <td><%= customer.address_street %></td>
        <td><%= customer.address_city %></td>
        <td><%= customer.address_state %></td>
        <td><%= customer.postal_code %></td>
        <td><%= customer.phone %></td>
        <td><%=l customer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_path(customer), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_path(customer),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_path,
            :class => 'btn btn-primary' %>

app/views/customers/new.html.erb
<%- model_class = Customer -%>

<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/show.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name_first) %>:</strong></dt>
  <dd><%= @customer.name_first %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name_last) %>:</strong></dt>
  <dd><%= @customer.name_last %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name_company) %>:</strong></dt>
  <dd><%= @customer.name_company %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @customer.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address_street) %>:</strong></dt>
  <dd><%= @customer.address_street %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address_city) %>:</strong></dt>
  <dd><%= @customer.address_city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address_state) %>:</strong></dt>
  <dd><%= @customer.address_state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:postal_code) %>:</strong></dt>
  <dd><%= @customer.postal_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @customer.phone %></dd>
</dl>
<%= image_tag @customer.image_url(:thumb).to_s %>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              customers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_path(@customer), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_path(@customer),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "CRM Test" %></li>
          <li><%= link_to "" %></li>
          <li><%= link_to "" %></li>
          <li><%= link_to "" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
  <title>CRM Test</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

  <%= yield %>
</div>


</body>
</html>